Information about time in speaking
Dudek03/GryllotalpaBot pull request #13
Opened 2023-02-09 14:09 UTC by n2oneProgrammer

2023-02-09 23:52 UTC, jaanonim requested changes
Some wrong naming and one wrong code organisation.

2023-02-09 23:52 UTC, jaanonim commented on modules/server_statisticts/voice_statistics.py
> +    async def search_meme(self, ctx, channel: discord.VoiceChannel):
I don't think name 'search_meme' is right here. 🙃

2023-02-09 23:52 UTC, jaanonim commented on utils/database.py
> +    def add_time_on_channel(self, server_id: int, channel_id: int, user_id: int, timeChannel: int):
I'm afraid that if we will ad all data base operations in here, this file will be giaiant. 


To do: split database.py into many modules base on functionality (eg. Voice statisic)

2023-02-09 23:52 UTC, jaanonim commented on modules/server_statisticts/voice_channels_statistic.py
> +rows = dict()
I don't see use of this variable. (if in use should be class atribute)

2023-02-09 23:52 UTC, jaanonim commented on modules/server_statisticts/voice_statistics.py
> +    async def top10_voice_channels(self, ctx):
This naming is miss leading. ( for me it mean: "top ten most popular voise channels" not "top ten most active people's on all voice channels")

2023-02-09 23:52 UTC, jaanonim commented on models/connection_time.py
> +    date: Mapped[int]
Timestamp or datatime would be better name because date suggest that this is only date without time

2023-02-14 06:53 UTC, jaanonim approved these changes
LGTM

2023-02-14 15:34 UTC, Dudek03 approved these changes

2023-02-14 15:34 UTC, merged